<%@ Page Title="" Language="C#" MasterPageFile="~/admin/Admin.master" AutoEventWireup="true" CodeFile="ManageMovies.aspx.cs" Inherits="admin_ManageMovies" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <link rel="stylesheet" type="text/css" href="../asset/css/ManageMovie.css" />
    <div class="container">
        <h2>Manage Movies</h2>

        <!-- Add/Edit Movie Form -->
        <div class="form-container">
            <h3>Add/Edit Movie</h3>
                <div class="form-group">
                    <label for="MovieTitle">Movie Title:</label>
                    <asp:TextBox ID="MovieTitle" runat="server" CssClass="input-field" required="true" />
                </div>
                <div class="form-group">
                    <label for="Description">Description:</label>
                    <asp:TextBox ID="Description" runat="server" CssClass="input-field" TextMode="MultiLine" required="true" />
                </div>
                <div class="form-group">
                    <label for="ReleaseDate">Release Date:</label>
                    <asp:TextBox ID="ReleaseDate" runat="server" CssClass="input-field" 
                        required="true" TextMode="Date" />
                </div>
                <div class="form-group">
                    <label for="Duration">Duration (in minutes):</label>
                    <asp:TextBox ID="Duration" runat="server" CssClass="input-field" required="true" />
                </div>
                <div class="form-group">
                    <label for="Genre">Genre:</label>
                    <asp:TextBox ID="Genre" runat="server" CssClass="input-field" required="true" />
                </div>
                <div class="form-group">
                    <label for="Language">Language:</label>
                    <asp:TextBox ID="Language" runat="server" CssClass="input-field" required="true" />
                </div>
                <div class="form-group">
                    <label for="PosterUpload">Upload Poster Image:</label>
                    <asp:FileUpload ID="PosterUpload" runat="server" CssClass="input-field" />
                </div>
                <div class="form-group">
                    <asp:Button ID="AddEditMovieButton" runat="server" Text="Add Movie" CssClass="btn" OnClick="AddEditMovieButton_Click" />
                    &nbsp;<asp:Button ID="DeleteMovieButton" runat="server" Text="Delete Movie" CssClass="btn" OnClick="DeleteMovieButton_Click" Visible="false" />
                </div>
                <asp:Label ID="MessageLabel" runat="server" CssClass="message"></asp:Label>
        </div>

        <!-- Movie List Grid -->
        <div class="list">
            <h3>Movies List</h3>
            <asp:GridView ID="MoviesGridView" runat="server" AutoGenerateColumns="False"  
                CssClass="grid" 
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                DataKeyNames="MovieId" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:BoundField DataField="MovieId" HeaderText="MovieId" 
                        SortExpression="MovieId" InsertVisible="False" ReadOnly="True" />
                    <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                    <asp:BoundField DataField="ReleaseDate" HeaderText="ReleaseDate" 
                        SortExpression="ReleaseDate" />
                    <asp:BoundField DataField="Duration" HeaderText="Duration" SortExpression="Duration" />
                    <asp:BoundField DataField="Genre" HeaderText="Genre" SortExpression="Genre" />
                    <asp:BoundField DataField="Language" HeaderText="Language" SortExpression="Language" />
                    <asp:ImageField DataImageUrlField="PosterURL" HeaderText="PosterImage">
                        <ControlStyle Width="300px" />
                    </asp:ImageField>
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                DeleteCommand="DELETE FROM [Movies] WHERE [MovieId] = @MovieId" 
                InsertCommand="INSERT INTO [Movies] ([Title], [Description], [ReleaseDate], [Duration], [Genre], [Language], [PosterURL]) VALUES (@Title, @Description, @ReleaseDate, @Duration, @Genre, @Language, @PosterURL)" 
                SelectCommand="SELECT * FROM [Movies]" 
                UpdateCommand="UPDATE [Movies] SET [Title] = @Title, [Description] = @Description, [ReleaseDate] = @ReleaseDate, [Duration] = @Duration, [Genre] = @Genre, [Language] = @Language, [PosterURL] = @PosterURL WHERE [MovieId] = @MovieId">
                <DeleteParameters>
                    <asp:Parameter Name="MovieId" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Title" Type="String" />
                    <asp:Parameter Name="Description" Type="String" />
                    <asp:Parameter DbType="Date" Name="ReleaseDate" />
                    <asp:Parameter Name="Duration" Type="Int32" />
                    <asp:Parameter Name="Genre" Type="String" />
                    <asp:Parameter Name="Language" Type="String" />
                    <asp:Parameter Name="PosterURL" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Title" Type="String" />
                    <asp:Parameter Name="Description" Type="String" />
                    <asp:Parameter DbType="Date" Name="ReleaseDate" />
                    <asp:Parameter Name="Duration" Type="Int32" />
                    <asp:Parameter Name="Genre" Type="String" />
                    <asp:Parameter Name="Language" Type="String" />
                    <asp:Parameter Name="PosterURL" Type="String" />
                    <asp:Parameter Name="MovieId" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </div>
    </div>
</asp:Content>

